# Generated by Django 5.2.4 on 2025-07-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('fulltime', 'Full-Time'), ('parttime', 'Part-Time'), ('intern', 'Internship'), ('contract', 'Contract'), ('remote', 'Remote')], max_length=20)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('vacancies', models.PositiveIntegerField()),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
