# Generated by Django 5.2.4 on 2025-07-25 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kyc_registration_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='full_name',
            new_name='full_namee',
        ),
    ]
